# Generated by Django 5.2.1 on 2025-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('temperature_c', models.IntegerField()),
                ('condition', models.CharField(max_length=64)),
            ],
        ),
    ]
